### ISSUE TITLE
Need some clarification on SlackDefaultSignInWorkspace

### ISSUE THREAD

**Issue by perfectly-preserved-pie** [Jamf-Custom-Profile-Schemas/ProfileManifestsMirror#2]
For https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror/blob/main/manifests/ManagedPreferencesApplications/com.tinyspeck.slackmacgap.json

```
 "SlackDefaultSignInWorkspace": {
            "type": "string",
            "title": "Default Workspace",
            "description": "Sets the default workspace for Slack sign-ins.",
            "links": [
                {
                    "rel": "More information",
                    "href": "https://slack.com/help/articles/360041725993-Share-a-default-sign-in-file-with-members"
                }
            ],
            "property_order": 10 

```

What value is expected here? Should it be the "friendly" name, i.e contoso.slack.com? or the Slack Team ID, i.e T7THYRTMD?

**Comment by apizz** [comment]
I asked the same question as the documentation doesn't make it as clear as it might.  But it's the team ID.
