### ISSUE TITLE
Fix Nudge Json

### ISSUE THREAD

**Issue by kylejericson** [Jamf-Custom-Profile-Schemas/ProfileManifestsMirror#20]
The Nudge payload in here ie messed up. Can you add the one from the Nudge GitHub?

https://github.com/macadmins/nudge/blob/main/Schema/jamf/com.github.macadmins.Nudge.json

**Comment by homebysix** [comment]
Please [submit manifest change suggestions upstream](https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror#submit-manifest-changes-upstream). Thank you!
