### ISSUE TITLE
Allow Tenant Key Issue

### ISSUE THREAD

**Issue by vandehey** [Jamf-Custom-Profile-Schemas/ProfileManifestsMirror#21]
I'm trying to set a tenant key for AllowTenantList. When I do this, the plist preview, and what hits my mac is malformed. Here is a snip of what I'm getting w/ this JSON:

```
<key>AllowTenantList</key>
    <dict>
      <key>{{key}}</key>
      <string>REDACTED</string>
      <key>{{value}}</key>
      <true/>
    </dict> 
```

What I would expect is: 

```
<key>AllowTenantList</key>
  <array>
   <dict>
    <key>REDACTED</key>
    <true/>
   </dict>
  </array>
```

**Comment by apizz** [comment]
Pls review https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror#submit-manifest-changes-upstream

**Comment by apizz** [comment]
when you submit, please include both the manifest and key that is problematic
