### ISSUE TITLE
Support for New Teams in com.microsoft.autoupdate2.json

### ISSUE THREAD

**Issue by andrewvalentine** [Jamf-Custom-Profile-Schemas/ProfileManifestsMirror#24]
The Application ID for New Teams is:

```TEAMS21```

Can support for this be incorporated into the Microsoft Autoupdate schema?

https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror/blob/main/manifests/ManagedPreferencesApplications/com.microsoft.autoupdate2.json

**Comment by homebysix** [comment]
As mentioned in the read me:

> Any corrections, additions, or modifications to the manifests in this repository should be submitted upstream to the [ProfileManifests](https://github.com/ProfileCreator/ProfileManifests) repository. Once pull requests are merged there, subsequent builds of this repository will include the changes.
