### ISSUE TITLE
Build runner failures

### ISSUE THREAD

**Issue by apizz** [Jamf-Custom-Profile-Schemas/ProfileManifestsMirror#25]
Since the last build updates this has been failing. Haven't been able to decipher what the issue is.

**Comment by apizz** [comment]
Builds have been failing for a while now so this repo hasn't been updating. Unclear from logs if this is malformed manifest, bug in script that builds, or combo of both. Last run: https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror/actions/runs/9170875862/job/25321793688

cc @homebysix

**Comment by homebysix** [comment]
Good callout — I'm looking into this now while at MacAD.uk, will try to fix soon.
