### ISSUE TITLE
menu.nomad.login.ad.json JSON Manifest Displays Errors in Jamf Pro

### ISSUE THREAD

**Issue by uurazzle** [Jamf-Custom-Profile-Schemas/ProfileManifestsMirror#3]
FYI:

Thanks for creating the JSON manifest.

The menu.nomad.login.ad.json JSON Manifest displays invalid JSON errors in Jamf Pro but passes JSON linter validation JSONLint <https://jsonlint.com>. This JSON Manifest works... 

https://github.com/Jamf-Custom-Profile-Schemas/ljcacioppo-schemas/blob/main/menu.nomad.login.ad.json

**Comment by apizz** [comment]
I isolated the issue to preference keys with a data type Jamf doesn't accept: `data`.  There are 2 preferences with this type - `BackgroundImageData` & `LoginLogoData` -  and once removed the error is not produced.

@homebysix I have to imagine there's a fairly easy way we can exclude any preferences with a value type of `data` from these json schemas

**Comment by homebysix** [comment]
Thanks! I think I solved this with 9d4ffdb.
