### ISSUE TITLE
com.microsoft.autoupdate2 missing licensing info for MAU

### ISSUE THREAD

**Issue by staze** [Jamf-Custom-Profile-Schemas/ProfileManifestsMirror#31]
com.microsoft.autoupdate2 is missing the licensing info here: 
https://learn.microsoft.com/en-us/microsoft-365-apps/mac/mau-set-license-info

This document is not terribly verbose in the available license types. It's also exceedingly hard to tell if these actually DO anything. The article started out as indicating it was only required for specific versions of Office (if you got stuck at 16.79), but then they removed that language and now it's indicated it's needed for all versions. =/

There seem to be, at least these 4 license activation types:
Subscription
2019-Consumer
2021-Consumer
2021-Commercial

Consumer and subscription licenses types referenced in KB linked. 2021-Commercial was discovered by someone in macadmin community I believe. 

Unclear if 2024 has any.

We currently have these set via custom attributes in Jamf, but would be nice if these could be added to the schema. 

Example (for O365): 

```
    <key>AppCustomPref</key>
    <dict>
      <key>/Applications/Microsoft Excel.app</key>
      <dict>
        <key>OfficeActivationLicense</key>
        <string>Subscription</string>
      </dict>
      <key>/Applications/Microsoft Word.app</key>
      <dict>
        <key>OfficeActivationLicense</key>
        <string>Subscription</string>
      </dict>
      <key>/Applications/Microsoft PowerPoint.app</key>
      <dict>
        <key>OfficeActivationLicense</key>
        <string>Subscription</string>
      </dict>
      <key>/Applications/Microsoft Outlook.app</key>
      <dict>
        <key>OfficeActivationLicense</key>
        <string>Subscription</string>
      </dict>
    </dict>
```

Example (for 2021 LTSC)

```
    <key>AppCustomPref</key>
    <dict>
      <key>/Applications/Microsoft Excel.app</key>
      <dict>
        <key>OfficeActivationLicense</key>
        <string>2021-Commercial</string>
      </dict>
      <key>/Applications/Microsoft Word.app</key>
      <dict>
        <key>OfficeActivationLicense</key>
        <string>2021-Commercial</string>
      </dict>
      <key>/Applications/Microsoft PowerPoint.app</key>
      <dict>
        <key>OfficeActivationLicense</key>
        <string>2021-Commercial</string>
      </dict>
      <key>/Applications/Microsoft Outlook.app</key>
      <dict>
        <key>OfficeActivationLicense</key>
        <string>2021-Commercial</string>
      </dict>
    </dict>
```

**Comment by apizz** [comment]
As the readme on this repo says this is just a mirror for another repo. Please feel free to create an issue over there if there's something you think needs adding / fixing

**Comment by staze** [comment]
Hi @apizz  I'm confused. https://github.com/ProfileCreator/ProfileManifests is just plists, no json schemas that I see. So are these just generated from the plists?

**Comment by apizz** [comment]
Yep. If there's something on the repo main readme that you feel could be worded differently to make that clear, please let us know!

**Comment by staze** [comment]
Nope, apparently I just can't read. Was pointed here from macadmins slack to try to update updated autoupdate2 schema and sadly doesn't work (see other issue), though sounds like that's also possibly from upstream. I see fix now. 

Thanks!
