### ISSUE TITLE
com.apple.applicationaccess-macOS.json missing key

### ISSUE THREAD

**Issue by staze** [Jamf-Custom-Profile-Schemas/ProfileManifestsMirror#6]
Missing allowGameCenter (and related keys) from com.apple.applicationaccess-macOS.json

https://developer.apple.com/documentation/devicemanagement/restrictions

**Comment by apizz** [comment]
@staze let me know if this incorporates the preferences you were looking for https://github.com/ProfileCreator/ProfileManifests/pull/515

**Comment by staze** [comment]
This does look like it adds the missing key. 

Thanks!

**Comment by staze** [comment]
Just a heads up, the "Allow Game Center Friends" looks like it has the same title.

        "allowGameCenter": {
            "type": "boolean",
            "title": "Allow Game Center",
            "default": true,
            "property_order": 145
        },
        "allowAddingGameCenterFriends": {
            "type": "boolean",
            "title": "Allow Game Center",
            "default": true,
            "property_order": 150
        },
