### ISSUE TITLE
Microsoft AutoUpdate json invalid

### ISSUE THREAD

**Issue by opus-nbo** [Jamf-Custom-Profile-Schemas/ProfileManifestsMirror#8]
https://github.com/Jamf-Custom-Profile-Schemas/ProfileManifestsMirror/blob/main/manifests/ManagedPreferencesApplications/com.microsoft.autoupdate2.json

Jamf says JSON is invalid. JSON Validator says, it's not.

**Comment by homebysix** [comment]
I dug into this, and it seems the part Jamf doesn't like is the `date` type, which appears in several dictionaries like this:

```
"ForcedUpdateDate": {
    "type": "date",
    "title": "Forced Update Date",
    "description": "The date and time to force the update."
},
```

In the resulting plist, this key type should be `date`, so this might be a bug in Jamf's validation.

**Comment by Artos254** [comment]
> I dug into this, and it seems the part Jamf doesn't like is the `date` type, which appears in several dictionaries like this:
> 
> ```
> "ForcedUpdateDate": {
>     "type": "date",
>     "title": "Forced Update Date",
>     "description": "The date and time to force the update."
> },
> ```
> 
> In the resulting plist, this key type should be `date`, so this might be a bug in Jamf's validation (PI110413).

I removed all entries of that quoted text and it worked! Thank you so much.

**Comment by SkylerGodfrey** [comment]
Hello, please correct me if I'm wrong but from my understanding JSON Schema does not accept `"type": "data"`and only accepts date as a format of string, `"type": "string", "format": "date"`. 

Not all JSON validators seem to check for the correct `"type"`. An example, https://jsonlint.com/ says the JSON is valid but just below the input box they have a note "Dates, and similar object types, aren't adequately supported and should be converted to strings". I personally prefer https://www.jsonschemavalidator.net/ which does match Jamf's validator in the `"type": "data"` being invalid. 

All this being said, there is a feature request to have Jamf handle the date formatted string and convert it to the plist date so please upvote that here: https://ideas.jamf.com/ideas/JN-I-15984 . This will require the JSON being updated to the `"type": "string", "format": "date"`. I'd be more than happy to submit a pull request as needed. 

I have not done any testing to confirm if Microsoft can handle the date formatted as a string or not.
